name: Sync Tags and Releases
on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 獲取所有歷史記錄
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Baron-von-Riedesel/HX.git
      - name: Fetch upstream tags
        run: |
          git fetch upstream --tags
      - name: Push tags to fork
        run: |
          git push origin --tags
